### PR TITLE
chore: bump blsttc from 3.1.0 to 5.1.0

### PR DESCRIPTION
**Pull request by dan-da**
We also:
    
* bump rand from 0.7.3 to 0.8.5
* bump rand_core from 0.5.1 to 0.6.3
* bump xor_name from 3.0.0 to 4.0.0
* minor code fixups to accomodate changes in deps.

These make us compatible with deps in blsttc.

-----

tests are passing locally.

```
running 6 tests
test key_gen::tests::having_min_unresponsive_nodes_cause_block ... ok
test key_gen::tests::all_nodes_being_responsive ... ok
test key_gen::tests::threshold_encrypt ... ok
test key_gen::tests::threshold_signature ... ok
test key_gen::tests::having_max_unresponsive_nodes_still_work ... ok
test key_gen::tests::network_churning has been running for over 60 seconds
test key_gen::tests::network_churning ... ok

test result: ok. 6 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 224.22s

   Doc-tests bls_dkg

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

### CODE REVIEW

**Comment by davidrusu** [comment]
@iancoleman I think you had mentioned that you had done this update to bls_dkg in one of your branches? Want to look this over and see if it's equivalent?

**Review by davidrusu — DISMISSED** [review]
LGTM

**Comment by iancoleman** [comment]
This matches my local changes to bls_dkg (not exactly but in effect they are the same) so LGTM.

I didn't import `ff::Field` and changed `sk_val = Fr::default()`

I don't have `.ok()?` on `poly.interpolate` L980 of mod.rs

**Comment by dan-da** [comment]
i will re-work this a bit to accomodate changes in #123.

**Review by davidrusu — APPROVED** [review]
re-approving

**Pull request merged**
